name: Tüm Repoyu Tek Yapma

on:
  workflow_dispatch:

env:
  M3U_REPO_TOKEN: ${{ secrets.M3U_REPO_TOKEN }} 

jobs:          
  push-m3u-to-root:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Checkout private_py repo
        uses: actions/checkout@v4
        with:
          repository: MDuymaz/tumsistem
          token: ${{ secrets.M3U_REPO_TOKEN }}
          path: private_py
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run birleştirici / üretici scriptleri
        run: python private_py/repotekyapma.py

      - name: Checkout private m3u8file repo
        uses: actions/checkout@v4
        with:
          repository: MDuymaz/m3urepo
          token: ${{ secrets.GH_TOKEN }}
          path: private_m3u8file
          fetch-depth: 1

      - name: Copy all M3U files to root of m3u8file repo
        run: |
          find . -maxdepth 2 -type f -name "*.m3u" -exec cp {} private_m3u8file/ \;

      - name: Commit and push M3U files
        run: |
          cd private_m3u8file
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.m3u || echo "No M3U to add"
          git diff --cached --quiet || git commit -m "Tüm M3U dosyaları güncellendi [auto]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymaz/m3urepo.git
          git push origin master
